name: Release

on:
  push:
    branches: [ "main" ]
    paths:
      - "VERSION"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Cache NDK
      id: cache-ndk
      uses: actions/cache@v3
      with:
        key: android-ndk-r25c-cache
        path: ~/android-ndk-r25c

    - name: Set up NDK
      if: steps.cache-ndk.outputs.cache-hit != 'true'
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25c
        add-to-path: false
      
    - name: Move NDK
      if: steps.cache-ndk.outputs.cache-hit != 'true'
      run: mv ${{ steps.setup-ndk.outputs.ndk-path }} ${HOME}/android-ndk-r25c

    - name: Install compilers
      run: |
        sudo apt update
        sudo apt install gcc-mingw-w64-x86-64 gcc gcc-aarch64-linux-gnu -y

    - name: Download macOS SDK
      if: steps.cache-theos.outputs.cache-hit != 'true'
      run: |
        curl -LO https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.0.sdk.tar.xz
        tar -xJf MacOSX11.0.sdk.tar.xz
        rm MacOSX11.0.sdk.tar.xz
        mv MacOSX11.0.sdk ~/theos/sdks/MacOSX11.0.sdk

    - name: Build
      run: |
        make all

    - name: Provide release version
        id: release_version
        run: echo v"release_version=$(cat VERSION)"  >> $GITHUB_OUTPUT

    - name: Release
      uses: softprops/action-gh-release@v0.1.14
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.release_version.outputs.release_version }}
        files: |
          build/*
