name: Check

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install compiler
      run: |
        sudo apt update
        sudo apt install gcc -y

    - name: Build
      run: |
        make linux-amd64
